# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      
      - name: Shutdown Default Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
        
      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'my_db'
          mysql user: root
          mysql password: root
          
      - name: Start MySQL
        run: sudo service mysql start
        
      - name: Verify MySQL
        run: mysql --user=root --password=root
        
      - name: Create nutrecipe Database
        run: mysql --user=root --password=root --execute="CREATE DATABASE IF NOT EXISTS nutrecipe;"
        
      - name: Create ingredients table
        run: mysql --user=root --password=root -D nutrecipe --execute="CREATE TABLE IF NOT EXISTS ingredients (ingredientId int NOT NULL AUTO_INCREMENT,product_name varchar(255) COLLATE utf8mb4_bin NOT NULL,ingredient_text text COLLATE utf8mb4_bin,carbohydrates float DEFAULT NULL,proteins float DEFAULT NULL,fats float DEFAULT NULL,salt float DEFAULT NULL,calories float DEFAULT NULL,nova_group char(1) COLLATE utf8mb4_bin DEFAULT NULL,categories text COLLATE utf8mb4_bin,serving_size varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,image text COLLATE utf8mb4_bin,createdAt datetime NOT NULL,updatedAt datetime NOT NULL,PRIMARY KEY (ingredientId)) ENGINE=InnoDB AUTO_INCREMENT=15726 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Create recipes table
        run: mysql --user=root --password=root -D nutrecipe --execute="CREATE TABLE IF NOT EXISTS recipes (recipeId int NOT NULL AUTO_INCREMENT,title varchar(255) COLLATE utf8mb4_bin NOT NULL,prep_time varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,cooking_time varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,rest_time varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,categories text COLLATE utf8mb4_bin,ingredients_list text COLLATE utf8mb4_bin,serving_size varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,instructions text COLLATE utf8mb4_bin,image text COLLATE utf8mb4_bin,createdAt datetime NOT NULL,updatedAt datetime NOT NULL,PRIMARY KEY (recipeId)) ENGINE=InnoDB AUTO_INCREMENT=2217 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Create users table
        run: mysql --user=root --password=root -D nutrecipe --execute="CREATE TABLE IF NOT EXISTS users (userId int NOT NULL AUTO_INCREMENT,last_name varchar(255) COLLATE utf8mb4_bin NOT NULL,first_name varchar(255) COLLATE utf8mb4_bin NOT NULL,phone_number varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,email varchar(255) COLLATE utf8mb4_bin NOT NULL,password varchar(255) COLLATE utf8mb4_bin NOT NULL,role varchar(255) COLLATE utf8mb4_bin NOT NULL,receiveEmail tinyint(1) DEFAULT NULL,receiveNotification tinyint(1) DEFAULT NULL,createdAt datetime NOT NULL,updatedAt datetime NOT NULL,PRIMARY KEY (userId)) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Insert a user
        run: mysql --user=root --password=root -D nutrecipe --execute=" INSERT IGNORE INTO users ( last_name , first_name , phone_number , email , password , role , receiveEmail , receiveNotification ) VALUES ( 'SEKPON' , 'ulysse' , '0000000000' , 'u.sekpon@gmail.com' , 'azerty' , 'admin' , true , false )"
        
      - name: Create bookmarkingredients table
        run: mysql --user=root --password=root -D nutrecipe --execute="CREATE TABLE IF NOT EXISTS bookmarkingredients ( id int NOT NULL AUTO_INCREMENT,ingredientId int NOT NULL,userId int NOT NULL,saved tinyint(1) NOT NULL,createdAt datetime NOT NULL,updatedAt datetime NOT NULL,PRIMARY KEY (id),KEY ingredientId (ingredientId),KEY userId (userId)) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Create bookmarkrecipes table
        run: mysql --user=root --password=root -D nutrecipe --execute="CREATE TABLE IF NOT EXISTS bookmarkrecipes ( id int NOT NULL AUTO_INCREMENT,recipeId int NOT NULL,userId int NOT NULL,saved tinyint(1) NOT NULL,createdAt datetime NOT NULL,updatedAt datetime NOT NULL,PRIMARY KEY (id),KEY recipeId (recipeId),KEY userId (userId)) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Show tables in nutrecipe Database
        run: mysql --user=root --password=root -D nutrecipe --execute="show tables;"
        
      - name: List existing SQL databases
        run: mysql --user=root --password=root --execute="show databases;"
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm ci
      #- run: npm run build --if-present

      - name: Unit tests
        run: npm run test
